name: Dependency Audit

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build dep-audit CLI
        run: npm run build

      - name: Run dep-audit
        run: node dist/index.js --severity moderate --gha

      - name: Upload annotations file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dep-audit-annotations
          path: annotations.json

      - name: Comment GitHub annotations
        if: success() || failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: annotations.json
          header: "Dependency Audit Annotations"
